@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class Board {
  - Board(): 
  + addCard(Card): void
  + cleanCards(): void
  + addCardObservers(Observer): void
   instance: Board
   cards: ArrayList<Card>
}
class Card {
  + Card(String, String): 
  + addForbiddenWords(ArrayList<String>): void
   forbiddenWords: ArrayList<String>
   word: String
   isRevealed: boolean
   color: String
}
class Category {
  + Category(): 
}
class ConfigWindowController {
  + ConfigWindowController(): 
  - isNumeric(String): boolean
  - onStartGame(): void
  + initialize(): void
  - showError(String, String): void
}
class Game {
  - Game(): 
  - initializeRevealedTiles(): void
  + revealTile(int, int): void
  - initializeBoard(): void
  - populateBoard(ArrayList<Card>, int): void
  + initializeGame(int, String, String, boolean): void
  + setPageManager(): void
  + addGuess(Guess): void
  - checkWinConditions(): void
  - stopTimer(): void
  + returnCard(Card): void
  - handleAssassinCard(): void
  + saveGame(): void
  + loadGame(): void
  + changeTurn(): void
  + startTimer(): void
  + submitClue(String, int): int
  - clueIsValid(String): boolean
  - getShuffledCards(String, int): ArrayList<Card>
  + isTileRevealed(int, int): boolean
   instance: Game
   blueReturned: int
   redReturned: int
   isTimerRunning: boolean
   nbCardsReturned: int
   timeLimit: int
   spyTurn: boolean
   boardSize: int
   blueBegin: boolean
   board: Board
   category: String
   lastGuess: Guess
   blueTurn: boolean
   imagesMode: boolean
}
class GameOverControllerBlueWin {
  + GameOverControllerBlueWin(): 
  + initialize(): void
}
class GameOverControllerRedWin {
  + GameOverControllerRedWin(): 
  + initialize(): void
}
class Guess {
  + Guess(String, int): 
   clue: String
   nbWords: int
}
class GuesserBoardController {
  + GuesserBoardController(): 
  - populateBoard(int): void
  - onCardClicked(StackPane, Card): void
  + initialize(): void
  + reagir(): void
  - convertColorToCSS(String): String
  - updateBackgroundColor(): void
}
class GuesserViewController {
  + GuesserViewController(): 
  - startAnimationAndCountdown(): void
  - updateBackground(): void
  - turn(): void
  - loadFrames(): void
  + reagir(): void
  - stopTimeLine(): void
  - action(): void
  + initialize(): void
}
class JsonReader {
  + JsonReader(): 
  + jsonReader(String, String, boolean): ArrayList<Card>
  + getCategories(String): Map<String, Category>
}
class Key {
  - Key(): 
  + addObserver(Observer): void
  - assignColorsToCards(): void
  + getCouleur(int, int): Color
  - initialiserGrille(): void
  + newKey(): void
  - notifyObservers(): void
   lignes: int
   colonnes: int
   instance: Key
}
class KeyController {
  + KeyController(): 
  - populateKeyGrid(int): void
  + initialize(): void
  - handleToggleKeyButton(): void
}
class Main {
  + Main(): 
  + main(String[]): void
  + start(Stage): void
}
class MenuBarController {
  + MenuBarController(): 
  - Sauvegarder(ActionEvent): void
  - Charger(ActionEvent): void
  + initialize(): void
  - RetourAcceuil(ActionEvent): void
}
class MenuWindowController {
  + MenuWindowController(): 
  - initialize(): void
  - openWebpage(String): void
}
interface Observer << interface >> {
  + reagir(): void
}
class PageManager {
  - PageManager(): 
  + loadGameOverViewBlueWin(): void
  + loadGuesserView(): void
  + loadSpyView(): void
  + loadConfigWindowView(): void
  + loadGameOverSpyViewBlueWin(): void
  + loadGameOverViewRedWin(): void
  + loadGameOverSpyViewRedWin(): void
  + closeSpyView(): void
  + loadMenuWindowView(): void
   guesserBoardController: GuesserBoardController
   instance: PageManager
   primaryStage: Stage
   spyBoardController: SpyBoardController
}
class Root {
  + Root(): 
}
class SpyBoardController {
  + SpyBoardController(): 
  + initialize(): void
  + reagir(): void
  - getNodeByRowColumnIndex(int, int, GridPane): StackPane?
  - updateBackgroundColor(): void
  - convertColorToCSS(String): String
  - populateBoard(int): void
  - updateRevealedTiles(): void
}
class SpyViewController {
  + SpyViewController(): 
  - updateBackground(): void
  + reagir(): void
  + initialize(): void
}
class Stats {
  + Stats(): 
  + toString(): String
  + incrementBlueTeamWins(): void
  + incrementGamesLaunched(): void
  + addCorrectGuesses(int): void
  + incrementRedTeamWins(): void
   blueTeamWins: int
   redTeamWins: int
   gamesLaunched: int
   totalCorrectGuesses: int
}
class Subject {
  + Subject(): 
  + ajouterObservateur(Observer): void
  + notifierObservateurs(): void
}
class TopGuesserController {
  + TopGuesserController(): 
  - startFading(): void
  + initialize(): void
  - stopFading(): void
  + reagir(): void
}
class TopSpyController {
  + TopSpyController(): 
  - startFading(): void
  + initialize(): void
  + reagir(): void
  + submitClue(): void
  - stopFading(): void
}
class Word {
  + Word(): 
}

Board                     "1" *-[#595959,plain]-> "cards\n*" Card                      
Card                       -[#000082,plain]-^  Subject                   
Category                  "1" *-[#595959,plain]-> "mots\n*" Word                      
ConfigWindowController    "1" *-[#595959,plain]-> "game\n1" Game                      
ConfigWindowController    "1" *-[#595959,plain]-> "key\n1" Key                       
ConfigWindowController    "1" *-[#595959,plain]-> "pageManager\n1" PageManager               
Game                      "1" *-[#595959,plain]-> "board\n1" Board                     
Game                       -[#595959,dashed]->  Guess                     : "«create»"
Game                      "1" *-[#595959,plain]-> "pageManager\n1" PageManager               
Game                       -[#000082,plain]-^  Subject                   
GameOverControllerBlueWin "1" *-[#595959,plain]-> "pageManager\n1" PageManager               
GameOverControllerRedWin  "1" *-[#595959,plain]-> "pageManager\n1" PageManager               
GuesserBoardController    "1" *-[#595959,plain]-> "board\n1" Board                     
GuesserBoardController    "1" *-[#595959,plain]-> "game\n1" Game                      
GuesserBoardController     -[#008200,dashed]-^  Observer                  
GuesserViewController     "1" *-[#595959,plain]-> "game\n1" Game                      
GuesserViewController     "1" *-[#595959,plain]-> "guesserBoardController\n1" GuesserBoardController    
GuesserViewController      -[#008200,dashed]-^  Observer                  
JsonReader                 -[#595959,dashed]->  Card                      : "«create»"
Key                       "1" *-[#595959,plain]-> "game\n1" Game                      
Key                       "1" *-[#595959,plain]-> "cards\n*" Observer                  
MenuBarController         "1" *-[#595959,plain]-> "game\n1" Game                      
MenuBarController         "1" *-[#595959,plain]-> "pageManager\n1" PageManager               
MenuWindowController      "1" *-[#595959,plain]-> "pageManager\n1" PageManager               
PageManager               "1" *-[#595959,plain]-> "guesserBoardController\n1" GuesserBoardController    
PageManager               "1" *-[#595959,plain]-> "spyBoardController\n1" SpyBoardController        
Root                      "1" *-[#595959,plain]-> "categories\n*" Category                  
SpyBoardController        "1" *-[#595959,plain]-> "board\n1" Board                     
SpyBoardController        "1" *-[#595959,plain]-> "game\n1" Game                      
SpyBoardController         -[#008200,dashed]-^  Observer                  
SpyViewController         "1" *-[#595959,plain]-> "game\n1" Game                      
SpyViewController          -[#008200,dashed]-^  Observer                  
SpyViewController         "1" *-[#595959,plain]-> "SpyBoardController\n1" SpyBoardController        
Subject                   "1" *-[#595959,plain]-> "observateurs\n*" Observer                  
TopGuesserController      "1" *-[#595959,plain]-> "game\n1" Game                      
TopGuesserController       -[#008200,dashed]-^  Observer                  
TopSpyController          "1" *-[#595959,plain]-> "game\n1" Game                      
TopSpyController           -[#008200,dashed]-^  Observer                  
@enduml
